//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn_DongPhongNha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Bill = new HashSet<Bill>();
            this.BillOfWareHouse = new HashSet<BillOfWareHouse>();
            this.BillOfWareHouse1 = new HashSet<BillOfWareHouse>();
            this.BillOfWareHouse2 = new HashSet<BillOfWareHouse>();
            this.BillOfWareHouse3 = new HashSet<BillOfWareHouse>();
            this.BillOfWareHouse4 = new HashSet<BillOfWareHouse>();
            this.BillOfWareHouse5 = new HashSet<BillOfWareHouse>();
        }
    
        public string userName { get; set; }
        public string passWord { get; set; }
        public string displayName { get; set; }
        public int typeAccount { get; set; }
        public string idStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual Staff Staff3 { get; set; }
        public virtual Staff Staff4 { get; set; }
        public virtual Staff Staff5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfWareHouse> BillOfWareHouse5 { get; set; }
    }
}
