//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn_DongPhongNha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillInfo = new HashSet<BillInfo>();
        }
    
        public int idBill { get; set; }
        public System.DateTime dateCheckIn { get; set; }
        public Nullable<System.DateTime> dateCheckOut { get; set; }
        public int idTable { get; set; }
        public int statusBill { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public string payerId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TableFood TableFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfo { get; set; }
    }
}
