//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAn_DongPhongNha
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfoOfWareHouse
    {
        public int idBillInfoOfWareHouse { get; set; }
        public Nullable<int> idBillOfWareHouse { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> number { get; set; }
        public int price { get; set; }
        public int totalPrice { get; set; }
    
        public virtual BillOfWareHouse BillOfWareHouse { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse1 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse2 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse3 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse4 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse5 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse6 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse7 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse8 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse9 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse10 { get; set; }
        public virtual BillOfWareHouse BillOfWareHouse11 { get; set; }
        public virtual Material Material { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual Material Material2 { get; set; }
        public virtual Material Material3 { get; set; }
        public virtual Material Material4 { get; set; }
        public virtual Material Material5 { get; set; }
        public virtual Material Material6 { get; set; }
        public virtual Material Material7 { get; set; }
        public virtual Material Material8 { get; set; }
        public virtual Material Material9 { get; set; }
        public virtual Material Material10 { get; set; }
        public virtual Material Material11 { get; set; }
    }
}
